version: '3.3'
services:
  postgres:
    image: postgres:10.3
    container_name: postgres-demo
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: diploma
      POSTGRES_DB: diploma
      POSTGRES_PASSWORD: 123qwe123
    volumes:
      - ./postgres-data:/var/lib/postgresql:rw
